<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function webform_custom_fields_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_settings_form' || $form_id == 'webform_add_form') {
    $webform = $form_state->getFormObject()->getEntity();

     // Field 1: Allow for this form to be attached to a supported user profile
    $form['allow_supported_user_profile'] = [
      '#type' => 'checkbox',
      '#title' => t('Allow for this form to be attached to a supported user profile'),
      '#default_value' => $webform->getThirdPartySetting('webform_custom_fields', 'allow_supported_user_profile', FALSE),
      '#weight' => -10,
    ];

    // Field 2: Who can submit this form?
    $form['who_can_submit'] = [
      '#type' => 'checkboxes',
      '#title' => t('Who can submit this form?*'),
      '#options' => [
        'admins' => t('Admins'),
        'mentors' => t('Mentors'),
        'supporters' => t('Supporters'),
        'supported_users' => t('Supported users'),
      ],
      '#default_value' => [
        'admins' => 'admins',
        'mentors' => 'mentors',
      ],
      '#disabled' =>  [
          'admins' => TRUE,
          'mentors' => TRUE,
          'mentors' => FALSE,
        ],
      '#states' => [
        'visible' => [
          ':input[name="allow_supported_user_profile"]' => ['checked' => TRUE],
        ],
      ],
      '#weight' => -9,
    ];

    // Field 3: Who can view results of this form?
    $form['who_can_view'] = [
      '#type' => 'checkboxes',
      '#title' => t('Who can view results of this form?*'),
      '#options' => [
        'admins' => t('Admins'),
        'mentors' => t('Mentors'),
        'supporters' => t('Supporters'),
        'supported_users' => t('Supported users'),
      ],
      '#default_value' => [
        'admins' => 'admins',
        'mentors' => 'mentors',
      ],
      '#disabled' => TRUE,
      '#states' => [
        'visible' => [
          ':input[name="allow_supported_user_profile"]' => ['checked' => TRUE],
        ],
      ],
      '#weight' => -8,
    ];

    // Field 4: Who can edit results of this form?
    $form['who_can_edit'] = [
      '#type' => 'checkboxes',
      '#title' => t('Who can edit results of this form?'),
      '#options' => [
        'admins' => t('Admins'),
        'mentors' => t('Mentors'),
        'supporters' => t('Supporters'),
        'supported_users' => t('Supported users'),
      ],
      '#default_value' => [
        'admins' => 'admins',
        'mentors' => 'mentors',
      ],
      '#disabled' => TRUE,
      '#states' => [
        'visible' => [
          ':input[name="allow_supported_user_profile"]' => ['checked' => TRUE],
        ],
      ],
      '#weight' => -7,
    ];

    // Field 5: Restrict by profile tag
    $form['restrict_by_profile_tag'] = [
      '#type' => 'checkbox',
      '#title' => t('Restrict by profile tag'),
      '#default_value' => $webform->getThirdPartySetting('webform_custom_fields', 'restrict_by_profile_tag', FALSE),
      '#states' => [
        'visible' => [
          ':input[name="allow_supported_user_profile"]' => ['checked' => TRUE],
        ],
      ],
      '#weight' => -6,
    ];

    // Field 6: Select Profile tags
    $form['select_profile_tags'] = [
      '#type' => 'entity_autocomplete',
      '#target_type' => 'profile_tag',
      '#tags' => TRUE,
      '#title' => t('Select Profile tags'),
      '#default_value' => $webform->getThirdPartySetting('webform_custom_fields', 'select_profile_tags', []),
      '#states' => [
        'visible' => [
          ':input[name="restrict_by_profile_tag"]' => ['checked' => TRUE],
        ],
      ],
      '#weight' => -5,
    ];

    $form['actions']['submit']['#submit'][] = 'webform_custom_fields_form_submit';


   }
}

/**
 * Custom submit handler for webform settings form.
 */
function webform_custom_fields_form_submit($form, FormStateInterface $form_state) {
  $webform = $form_state->getFormObject()->getEntity();
  $custom_field_value = $form_state->getValue('custom_field');
  $conditional_checkboxes_submit_value = $form_state->getValue('conditional_checkboxes_submit');
  $conditional_checkboxes_view_value = $form_state->getValue('conditional_checkboxes_view');
  $conditional_checkboxes_edit_value = $form_state->getValue('conditional_checkboxes_edit');

  // Save the custom field value and the conditional checkboxes values as third-party settings.
  $webform->setThirdPartySetting('webform_custom_fields', 'custom_field', $custom_field_value);
  $webform->setThirdPartySetting('webform_custom_fields', 'conditional_checkboxes_submit', array_filter($conditional_checkboxes_submit_value));
  $webform->setThirdPartySetting('webform_custom_fields', 'conditional_checkboxes_view', array_filter($conditional_checkboxes_view_value));
  $webform->setThirdPartySetting('webform_custom_fields', 'conditional_checkboxes_edit', array_filter($conditional_checkboxes_edit_value));
  $webform->save();
}

 

/**
 * Implements hook_views_data().
 */
function webform_custom_fields_views_data() {
  $data = [];

  $data['webform_submission']['webform_custom_field'] = [
    'title' => t('Custom Webform Field'),
    'help' => t('Displays the custom field value from webform entities.'),
    'field' => [
      'id' => 'webform_custom_field',
    ],
  ];

  return $data;
}